### ISSUE TITLE
Sidebar Is Misbehaving

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#109]
The bottom of the sidebar cannot be seen.

**Comment by candyj0311** [comment]
<img width="1269" alt="screen shot 2016-03-02 at 4 23 33 pm" src="https://cloud.githubusercontent.com/assets/10750162/13475882/274fb500-e093-11e5-91c0-d9669344f0a5.png">

**Comment by MakotoTheKnight** [comment]
Can you reproduce this on master as well?

**Comment by candyj0311** [comment]
Yes.

**Comment by candyj0311** [comment]
Let's see if this is fixed with the style changes. We want to fix this in order to continue testing the learning questions functionality, but since the rest of it looks good, it should be fine.
