### ISSUE TITLE
Address large "Add Districts" button

### ISSUE THREAD

**Issue by MakotoTheKnight** [MobilityLabs/pdredesign-server#123]
See referenced image:

![image](https://cloud.githubusercontent.com/assets/1821302/13708054/d1eb4614-e769-11e5-9644-357c7ef26948.png)

**Comment by rickymetz** [comment]
This also affects the the action buttons in the Draft form. I also imagine it touches the report page buttons as well.

**Comment by candyj0311** [comment]
Wait for next deploy to staging (this afternoon).

**Comment by juliosantos** [comment]
@rickymetz @candyj0311 @MakotoTheKnight  Sorry guys, I'm still new to this :) Could you explain what exactly needs addressing?

**Comment by MakotoTheKnight** [comment]
@juliosantos This particular PR revolves around fixing the two links "Manage Participants" and "Add New Participants" by unifying their style with the "Recommend Assessment" button found on the home page.

![image](https://cloud.githubusercontent.com/assets/1821302/13849711/e97ed860-ec1c-11e5-8451-900eda650ba6.png)

To get to that page, log in to an account locally and create a new assessment.  They live in Step 2.
