### ISSUE TITLE
Userflow flow spreadsheet

### ISSUE THREAD

**Issue by rickymetz** [MobilityLabs/pdredesign-server#124]
Create a spreadsheet that ties each step of the userflow to a html link/mockup/or issue.

This is to ensure that every end-user task has been covered/addressed.

**Comment by seanperkins** [comment]
Add individual user flows and add details for filling out assessment and filling out inventory

**Comment by candyj0311** [comment]
Still needs links to mockups

**Comment by rickymetz** [comment]
Should be completed EOD 3/28/26
