### ISSUE TITLE
Users Can Share An Inventory Report By Link

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#127]
Works for Readiness Assessment. Will need to be used for Inventory. @HeyCat Will you please add the updated share link design?

**Comment by candyj0311** [comment]
Depends on #184

**Comment by bithavoc** [comment]
@HeyCat any chance you could add the updated readonly view for the shared report? I'm guessing it'd be similar to the one attached in #194 but entirely readonly.

**Comment by HeyCat** [comment]
![inventory_report_not_logged_in](https://cloud.githubusercontent.com/assets/5464910/14725268/d497b20e-07e8-11e6-883e-80cae01dcfd6.png)
