### ISSUE TITLE
Rails Assets - Update link

### ISSUE THREAD

**Issue by MakotoTheKnight** [MobilityLabs/pdredesign-server#128]
rails-assets.org is shutting down.  For a temporary fix, we are planning to switch over to the available mirror https://rails-assets.tenex.tech/, which has support at least through the end of 2016.

**Comment by candyj0311** [comment]
This may need to be brought over with other cherry picked items

**Comment by MakotoTheKnight** [comment]
The deadline on this is the 31st.

**Comment by MakotoTheKnight** [comment]
According to https://github.com/rails-assets/rails-assets/issues/312, it seems that the migration is going to happen mostly transparently to end users.  That is to say, the domain `rails-assets.org` is going to be maintained, and the server will live somewhere else.

This is great news in that we do not need to do anything, but we will be vigilant towards the transition.
