### ISSUE TITLE
Product Inventory: Create Page to Product Inventory: Break out elements on assign.html into components

### ISSUE THREAD

**Issue by MakotoTheKnight** [MobilityLabs/pdredesign-server#131]
Generify the existing assessment facilitation page and use it for product inventories.

This should be the location where new product inventories land after they are created.

**Comment by candyj0311** [comment]
This includes the edit screen.

**Comment by candyj0311** [comment]
This includes the Edit Screen.

**Comment by candyj0311** [comment]
@MakotoTheKnight will break this task down.

**Comment by MakotoTheKnight** [comment]
Changed scope of task:  this will only cover the decomposition of the components.   Integrating them into one single page will happen in a separate task.
