### ISSUE TITLE
Add additional buttons for adding participants and separate modals

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#132]

**Comment by rickymetz** [comment]
Mockup here: https://drive.google.com/a/mobility-labs.com/file/d/0B-nCEm5iPUjibGNCUk9XOU9NemM/view

**Comment by MakotoTheKnight** [comment]
Principle objective:  Each component of those menus should be a modal.  One of them already is, but what exists encompasses all three of them.

The tabs code should only be used here and it should be removed.  We may have a need for it in the future, but we can rely on Git to resurrect that code for us if we need it.

The style on these links will change and we should look into a way to reuse those as part of a directive.

**Comment by MakotoTheKnight** [comment]
Ensure that these buttons exist in the correct places in addition to the creation page:

 - Dashboard
 - Report

**Comment by MakotoTheKnight** [comment]
This depends on #131, chiefly due to the way that we've broken out the directive for inviting participants.
