### ISSUE TITLE
D&T Inventory Dashboard Page

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#134]
This is the page where users can manage participants, send reminders, adjust the inventory schedule, add/view learning questions (and edit their own), and view the report. 

Remember that the Learning Questions will be in a modal rather than the sidebar. @HeyCat, do you have a design that shows the Learning Questions button with the others?

**Comment by candyj0311** [comment]
@rickymetz Will you please attach the mockup?

**Comment by rickymetz** [comment]
@candyj0311 Will do.

**Comment by candyj0311** [comment]
@rickymetz Please add the mockup.

**Comment by rickymetz** [comment]
DTA or DTI dashboard page? They're two distinct pages.

**Comment by rickymetz** [comment]
## Inventory Dashboard

![Inventory Dashboard](https://cloud.githubusercontent.com/assets/2237073/14218923/3d99e912-f825-11e5-84dc-0f530efead78.png)

**Comment by candyj0311** [comment]
Thanks @rickymetz - We needed the Inventory. Updated the issue to reflect that.

**Comment by MakotoTheKnight** [comment]
Depends on #142, #143, and #155.

**Comment by candyj0311** [comment]
We are implementing the sidebar without the listing. The copy on "Modify Schedule" should read "Change Due Date."

**Comment by MakotoTheKnight** [comment]
All other behavior should be taken from the assessment page.  We are going to build out the sidebar to match the style, save for the listing of the learning questions.
