### ISSUE TITLE
Set Up Mandrill

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#141]

**Comment by candyj0311** [comment]
It's not letting me verify the domain, DKIM settings, or SPF settings via e-mail.

**Comment by candyj0311** [comment]
pdredesign.org now shows as verified, but DKIM settings and SPF settings show as missing. Reached out to support last week, but no response yet.

**Comment by candyj0311** [comment]
* Verify API keys correct
* update variables in Heroku to new API keys
* test setup with mail.pdredesign.org

**Comment by bithavoc** [comment]
Steps:
* Remove mandrill addon (for some reasons it leaves `MANDRILL_PASSWORD` which you replace with the mandrill API KEY)
* Add `MANDRILL_USERNAME` with the name of the mailchimp account
