### ISSUE TITLE
Product Inventory:  Create Page

### ISSUE THREAD

**Issue by MakotoTheKnight** [MobilityLabs/pdredesign-server#144]
Use the split-up modals from #131 to make this happen.

The create page should behave and look identical to the current create page for assessments.  The main changes to this page would be the resource being used; instead of using an Assessment, we would be using an Inventory.

 - [x] Add show route for Inventories
 - [x] Update view to remove duplicate buttons on both Inventory and Assessment
 - [x] Create inventory assign page
 - [x] Add support for inventories to CreateService
 - [x] Add inventory support to LearningQuestion
 - [ ] Add simple navigation for draft entries _only_
 - [x] Redirect inventory creation to this page

**Comment by candyj0311** [comment]
Add details once 131 is reviewed.

**Comment by MakotoTheKnight** [comment]
Wire in the functionality captured in pull #148 to this page.  The inventory should be using that functionality and behavior.

**Comment by MakotoTheKnight** [comment]
Depends on #142, #143, and #155.
