### ISSUE TITLE
User reports consensus page crashing

### ISSUE THREAD

**Issue by seanperkins** [MobilityLabs/pdredesign-server#147]
User reports:
Everything is going fine with the two assessments we have up so far.

 

When I try to look at it my old consensus form last year’s: I get this error and crashes the browser:

A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.

 

Script: http://pdredesign.org/assets/p…43241386530ce46ae399528c079.js:23052

Users consensus assessments have over 100 participants.

If you need email address, let me know.

Browser Details:
Operating System	Windows Windows 7
Screen Resolution	1024 x 768
Web Browser	Firefox 44.0
Browser Size	1024 x 634
IP Address	67.23.111.2
Color Depth	16
Javascript	Enabled
Flash Version	21.0.-1
Cookies	Enabled
User Agent	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0

**Comment by seanperkins** [comment]
Additional info
I usually use firefox (on mac) but it has also happened on safari.
Has happened with multiple older assessments

Happens with the following assessments:
AASA Miami Dade
AASA fulton County

**Comment by candyj0311** [comment]
It works in Firefox and Chrome - I'm even able to load the assessments with +100 participants as well as the 2 that Bryan mentioned having problems with.
