### ISSUE TITLE
Facilitator Who Creates Assessment Cannot Become Participant

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#150]
Users have the option of making a facilitator who creates an assessment a participant.  

When that facilitator is made a participant, it automatically reverts to facilitator. 

If that behavior is correct, we shouldn't present the choice. It seems like this situation is an edge case as far as facilitators creating an assessment and then wanting to act as participants.

**Comment by rickymetz** [comment]
Can confirm. This behavior is present at all levels of the Readiness assessment.
