### ISSUE TITLE
404 Appears Instead of Resource

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#152]
http://pdredesign.org/assets/PDRedesign%20RA%20Facilitation%20Guide.pdf

**Comment by MakotoTheKnight** [comment]
This was accidentally removed as part of commit 9f146ce.  The PDFs still exist in the history, so resurrecting them is not a difficult operation.

We will move these to a folder so that compiling assets does not interfere with them.

**Comment by MakotoTheKnight** [comment]
@bithavoc:  Could I get you to look at this PR?

**Comment by candyj0311** [comment]
LGTM.
