### ISSUE TITLE
Feature Toggle support for deploys

### ISSUE THREAD

**Issue by MakotoTheKnight** [MobilityLabs/pdredesign-server#157]
We will require a feature flag to deploy what we've got on staging to production.  Ideally, this should take the form of an environment flag which guards parts of our UI from a code path we are not ready to expose.

- [ ] Create table to capture feature name and if it's enabled, indexed on name (no ID)
- [ ] Create endpoint to leverage table
- [ ] Create V1 API controller for feature toggles
- [ ] Create seed data for staging and production (seed desired feature ON in staging, OFF in production)
- [ ] Create Angular resource to determine if feature is eligible to be seen, with caching
- [ ] Hide feature using `ng-if`

**Comment by seanperkins** [comment]
Lets figure out what links should be hidden to prevent users from discovering Inventory/Landscape. I would like to get the new styles over to production soon.

**Comment by bithavoc** [comment]
Checklist:
*  Remove **Data & Tech audit** from navigation
* Remove **Manage participant** & **Add user** from assessment list (`entry_view.html`)
* Remove **Data & Tech** button from homepage
* Run migrations on **production**
* Check missing/newly introduced environment variables (if any)
