### ISSUE TITLE
Tests Inventory Permissions Ctrl and Permission submission form

### ISSUE THREAD

**Issue by bithavoc** [MobilityLabs/pdredesign-server#164]
In the inventory permissions feature, we'd need to revisit ManageInventoryPermissionsCtrl and how it's handling the form submission and test coverage.

Spotted in https://github.com/MobilityLabs/pdredesign-server/pull/160

**Comment by MakotoTheKnight** [comment]
No longer relevant to test as this particular code has been replaced.
