### ISSUE TITLE
Add links to about pages in main nav

### ISSUE THREAD

**Issue by rickymetz** [MobilityLabs/pdredesign-server#171]
Add About to Main Nav so dropdown reveals About PDredesign, About RA, About DT Inventory, About DT Analysis

**Comment by rickymetz** [comment]
dependant on #170 #169

**Comment by candyj0311** [comment]
Some possible addresses to be discussed with the tech team: https://docs.google.com/document/d/1ZtrSoJ0ntD5Cgl19Ozuzz2ANO-WTCv-R-SBuhgZNndo/edit

**Comment by candyj0311** [comment]
This will be done as a part of #182.
