### ISSUE TITLE
Edit Inventory Page:  Base Layout

### ISSUE THREAD

**Issue by MakotoTheKnight** [MobilityLabs/pdredesign-server#178]
Based on #177, we are going to be creating the base structure of this page.

There should be:

 - Non-functional buttons (Mark Inventory Complete, Save and Exit Inventory, Add product entry, Add data entry)
 - Correct copy for page
 - Learning Questions will list in its modal as opposed to the sidebar

**Comment by candyj0311** [comment]
Mockup reflecting change to LQs: https://drive.google.com/open?id=0Bw4mIkwr2DlaZzZDdzBtekhRUEE

**Comment by bithavoc** [comment]
Based on [the file attached in #177](https://github.com/MobilityLabs/pdredesign-server/issues/177#issuecomment-205347903), it doesn't seem like we have a clear design of how the page looks like when either the product list or the data entry lists are empty.

**Comment by bithavoc** [comment]
@HeyCat it'd be great to see how the Delete/Edit buttons work, it's only present in the "Data" list but I wonder if it should be part of the "Product" list as well.

* should we add checkboxes to each one of the rows in the list to select on which entries are we applying the Delete action?
* how does the confirmation message for Deletion looks like?
* can you clarify how the Edit button works? I would think the Edit part can be address in the details page once I click on either a product or data entry.

**Comment by bithavoc** [comment]
@HeyCat do we need to paginate the items for these lists? if that's the case, how many items do we ideally fetch per page?

**Comment by bithavoc** [comment]
@HeyCat can we see an example of the listing looks like when there are no items matching the search term?

also, based on which columns do we try to match the search term?

**Comment by HeyCat** [comment]
@candyj0311 and I working on these questions, if there are add/edit paradigms we already use, i would like to take advantage of the opportunity to be consistent. we will have answers for you shortly.

**Comment by HeyCat** [comment]
as far as the pagination, please paginate every 20 entries.

**Comment by HeyCat** [comment]
![add-product-entry](https://cloud.githubusercontent.com/assets/5464910/14259682/f02a96f6-fa75-11e5-8e0f-d9b89f2350c3.png)
![inventory_edit](https://cloud.githubusercontent.com/assets/5464910/14259683/f02a6596-fa75-11e5-885e-1a6b5b1a0707.png)

**Comment by HeyCat** [comment]
After evaluating the other edit/delete functionality in the learning questions, ultimately I don't think we can recycle that in-line edit/delete (with the font awesome pencil and "x"). My assumption is that a user that wants to edit or delete an item from this list has a vested interest in doing-so carefully. Therefore, when a user clicks "edit" (using the 3rd CTA style) the edit modal pops up. When the user scrolls through the modal, at the bottom, the user will see "save, cancel and delete." Clicking delete will then prompt an "are you sure?" pop-up. While I don't love the pop-ups on pop-ups, I think deleting such a potentially large list item warrants affirmation.

**Comment by HeyCat** [comment]
![inventory_no_results](https://cloud.githubusercontent.com/assets/5464910/14260062/ae923f1c-fa77-11e5-891c-e68fa6130a1d.png)

**Comment by HeyCat** [comment]
After discussing with sean, we will do the edit/delete inline, mock to come shortly.

**Comment by bithavoc** [comment]
@HeyCat I'm looking at the new screenshots, I see we got rid of the Delete button, but it'd be great if you could clarify how the Edit button works.

Also the Learning Questions piece you described, this is how assessment looks like now:

![](https://cloud.githubusercontent.com/assets/219289/14260719/7d130e12-fa72-11e5-84d0-826ab9fa25fb.png)

The design you attached looks like this:

![](https://cloud.githubusercontent.com/assets/219289/14260738/930c3eb4-fa72-11e5-81ef-c90836ea83a0.png)

It seems like we're supposed to show the questions in the side-bar now(which I think it should reside in it's own task), what other differences in behavior and design can you highlight here?

**Comment by candyj0311** [comment]
@bithavoc @HeyCat We're going to keep the modal for now and have created an enhancement to capture making the learning questions appear in the sidebar (which we can get to later if we decide there's a need). The Add/Review Learning Questions button can go with the other buttons above.

**Comment by HeyCat** [comment]
the edit button would take t he user to the modal to edit the inventory item, to which they could then save at the bottom.

**Comment by HeyCat** [comment]
After some discussions yesterday, we ultimately decided to keep the product/data edit and delete functionality inline. the user can click the edit (pencil) and the edit modal spawns, or the user can click the "x" and then a js comfirmation popup appears asking the user to confirm line item deletion.

**Comment by HeyCat** [comment]
![inventory_no_entries](https://cloud.githubusercontent.com/assets/5464910/14285327/06d76df4-fb19-11e5-88d6-bd10c8a82ece.png)
![inventory_no_results](https://cloud.githubusercontent.com/assets/5464910/14285325/06d3573c-fb19-11e5-8e49-ac82c0c1bc62.png)
![inventory_with_products](https://cloud.githubusercontent.com/assets/5464910/14285326/06d5c7ba-fb19-11e5-9f54-0d0b10136a13.png)

**Comment by bithavoc** [comment]
what's likely the route for this page, `/#/inventories/23` or `/#/inventories/23/edit`
