### ISSUE TITLE
Edit Inventory Page: Product Listing

### ISSUE THREAD

**Issue by MakotoTheKnight** [MobilityLabs/pdredesign-server#179]
Wire in the product listing.

 - Add filters and search bar
 - Add product listing (including information for product name, vendor, and "used for")

**Comment by bithavoc** [comment]
I'm noticing in the filters there is an option to filter by `Vendor`, it looks like a checkbox:

![](https://cloud.githubusercontent.com/assets/219289/14255058/07982b64-fa58-11e5-8cd6-9b5d5532218f.png)

However, in https://github.com/MobilityLabs/pdredesign-server/issues/104 `Vendor` is a text input:

![](https://cloud.githubusercontent.com/assets/219289/14255096/2e4bf1aa-fa58-11e5-86c2-ff9a88a6bd17.png)

Does this mean the filter/option to be layout out in https://github.com/MobilityLabs/pdredesign-server/issues/178 should be a textbox? If this is true, the [design attached to google drive in #177](https://github.com/MobilityLabs/pdredesign-server/issues/177#issuecomment-205347903) should be updated to show how a filter with text input would look like before we start working in #178

**Comment by bithavoc** [comment]
@seanperkins just clarified me that these are not filtering options, they are instead options to modify which columns are being presented in the data table.

**Comment by MakotoTheKnight** [comment]
@bithavoc:  Okay.  That makes defining what needs to be brought back with #183 a bit clearer.

**Comment by bithavoc** [comment]
@MakotoTheKnight do you think we need server side support to prevent all the remaining columns not being presented in the list from being fetched as part of the results or is this something we can address when it becomes a real perfomance issue?

**Comment by MakotoTheKnight** [comment]
@bithavoc My thought is that we can bring back all of these rows and filter them based on what we select in the view.

**Comment by seanperkins** [comment]
I would like to see what we are looking at performance wise if we just default to all fields in the endpoint initially. If we see that it becomes an issue with 30-50 inventory and data items, add additional filtering, otherwise, roll with what we have.

**Comment by seanperkins** [comment]
Looks like we are all in agreement to roll with all fields initially

**Comment by MakotoTheKnight** [comment]
After discussion, the product listing will not include the field for "Usage Data from Vendor".

**Comment by HeyCat** [comment]
![inventory_no_entries](https://cloud.githubusercontent.com/assets/5464910/14284550/049f6e72-fb16-11e5-99be-d8419fd39daa.png)
![inventory_no_results](https://cloud.githubusercontent.com/assets/5464910/14284548/049db960-fb16-11e5-9552-e3bdbc3463cf.png)
![inventory_with_products](https://cloud.githubusercontent.com/assets/5464910/14284549/049dd968-fb16-11e5-8e42-2abcd5cc5c64.png)

**Comment by HeyCat** [comment]
After some discussions yesterday, we ultimately decided to keep the product/data edit and delete functionality inline. the user can click the edit (pencil) and the edit modal spawns, or the user can click the "x" and then a js comfirmation popup appears asking the user to confirm line item deletion.

**Comment by HeyCat** [comment]
![inventory_one_product_entry_with_vendor_one_data](https://cloud.githubusercontent.com/assets/5464910/14323651/56a98818-fbef-11e5-9ed4-087c1ca5c825.png)

**Comment by HeyCat** [comment]
the pencil is the edit and it brings up the edit modal, the "x" brings up a js confirm to delete.

**Comment by juliosantos** [comment]
"Add product entry" ties into #104. Also, as soon as there's a list of product entries with an "edit" button, the product entry modal built in #104 will render it and allow for updating

**Comment by HeyCat** [comment]
![inventory_one_product_entry_with_vendor_one_data](https://cloud.githubusercontent.com/assets/5464910/14431461/cc99198e-ffd3-11e5-961c-77ff43381bc7.png)
