### ISSUE TITLE
Edit Inventory Page:  Data Listing

### ISSUE THREAD

**Issue by MakotoTheKnight** [MobilityLabs/pdredesign-server#181]
Wire in the data listing.

 - Add filters and search bar

**Comment by bithavoc** [comment]
What columns do we need to show for Data Entries?

**Comment by seanperkins** [comment]
Data Type
Data Capture
Who Enters Data
Who Accesses Data

**Comment by bithavoc** [comment]
Column matching:
* Data Type: `general_data_question.data_type` **?**
* Data Capture: `general_data_question.data_capture`
* Who Enters Data: `data_entry_question.who_enters_data`
* Who Access Data: `data_access_question.who_access_data`
