### ISSUE TITLE
About pages

### ISSUE THREAD

**Issue by seanperkins** [MobilityLabs/pdredesign-server#182]
Waiting for #170

**Comment by candyj0311** [comment]
I added this for 1.2 since we're working on getting this wrapped up with the 1.2 items we're working on.

**Comment by candyj0311** [comment]
@HeyCat Please add designs once copy is updated. We also need to add the routes.

**Comment by bithavoc** [comment]
**Routes:**
```
about/pdredesign
about/ra/assessment 
about/dt/inventory
about/dt/analysis

```

**Comment by candyj0311** [comment]
We need to attach the mockups from #170. There is one route from one page that goes to each about page.

**Comment by candyj0311** [comment]
about/dt/analysis
![](https://cloud.githubusercontent.com/assets/5464910/14572940/cc6dce7e-031f-11e6-891b-3ec2cff2ad43.png)

**Comment by candyj0311** [comment]
about/dt/inventory

![](https://cloud.githubusercontent.com/assets/5464910/14572941/cc7202d2-031f-11e6-8201-5a437b973699.png)

**Comment by candyj0311** [comment]
about/pdredesign
![](https://cloud.githubusercontent.com/assets/5464910/14572943/cc7cc168-031f-11e6-83ba-5c7604d2c1df.png)

**Comment by candyj0311** [comment]
about/ra/assessment
![](https://cloud.githubusercontent.com/assets/5464910/14572942/cc73bb72-031f-11e6-86ed-a052446bd558.png)

**Comment by candyj0311** [comment]
The updated copy is here: 
PDR: https://drive.google.com/open?id=1LOr0vu-LAxdttXeq7FQM91Qv1k8bv3G46ib0wXrcd3A
RA: https://drive.google.com/open?id=1FGCFRUw44RJJrmGaiynNQoLspQbYDO4OWL06W45rGRU
DTI: https://drive.google.com/open?id=1TU37zyJsUQcLa_2J1K8KYS0cS-Pe2cqdzTWteXy4HW8
DTA: https://drive.google.com/open?id=1MzKHhKsIYwSN1W4ENEDlqoLIWonZComwGBqQaIwLBCs

**Comment by HeyCat** [comment]
![about_ra_assessment](https://cloud.githubusercontent.com/assets/5464910/14887484/0c159c6a-0d24-11e6-8a47-6ab174546bc2.png)
![about_pdredesign](https://cloud.githubusercontent.com/assets/5464910/14887482/0c119fc0-0d24-11e6-87a9-414a070e9ef5.png)
![about_dt_inventory](https://cloud.githubusercontent.com/assets/5464910/14887483/0c1357f2-0d24-11e6-97cd-6fec712a0d66.png)
![about_dt_analysis](https://cloud.githubusercontent.com/assets/5464910/14887485/0c1627c0-0d24-11e6-87c7-f8b3c38509d1.png)

**Comment by candyj0311** [comment]
We'll nix shortening the link for now.

**Comment by juliosantos** [comment]
We'll also use numbers instead of process icons

**Comment by juliosantos** [comment]
Waiting for #229
