### ISSUE TITLE
Create /inventories/:id/products resource

### ISSUE THREAD

**Issue by MakotoTheKnight** [MobilityLabs/pdredesign-server#183]
For tasks #179 and #165, we require an endpoint to pull back a listing of product entries.

Data returned should be:

 - id
 - title
 - vendor
 - purpose (correlates to "Used for")
 - hosting (correlates to "Where is the data hosted?")
 - attached_to_other_products (boolean field)
 - single_sign_on
 - usage (represents staff usage)

**Comment by bithavoc** [comment]
I'll be researching what angular datatable component(likely to be http://l-lin.github.io/angular-datatables) we need and how the API would fit the needs of the data table backend.

**Comment by bithavoc** [comment]
@MakotoTheKnight 
in **Data returned should be**, is `title` supposed to be `product_name`?

**Comment by MakotoTheKnight** [comment]
We can likely call the resource `product_name`.  This was meant to correspond to the original version of these mockups found at https://drive.google.com/a/mobility-labs.com/file/d/0B-nCEm5iPUjiOG9GaGZQSWs5QkE/view.
