### ISSUE TITLE
Inventory Report Page

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#184]
On the Inventory Report Page, users can view the products and data added to the inventory. Much of this view can be taken from the page participants see when they add products and data sets (minus the ability to add/edit the items) with a different sidebar. Instead of "Meeting Already Held," copy should read "Inventory Up To Date."  There should also be a button to continue to an Analysis. 

We need a logged in version and a non logged in version. For facilitators, the logged in version allows the user to continue on to creating an analysis and to add high level takeaways, while the not logged in version does not. Facilitators and participants, when logged in, will have a way to access the page to edit the inventory.

**Comment by candyj0311** [comment]
![inventory-1](https://cloud.githubusercontent.com/assets/10750162/14426864/8a7e064a-ffbf-11e5-918a-e787dcc675f0.png)

![analysis-report__1_](https://cloud.githubusercontent.com/assets/10750162/14426869/90054308-ffbf-11e5-8869-1f14d028940a.png)

**Comment by HeyCat** [comment]
![inventory](https://cloud.githubusercontent.com/assets/5464910/14433231/7c1a719e-ffdb-11e5-8420-c734892c1de0.png)

**Comment by candyj0311** [comment]
We need to discuss whether this is a living inventory or ever has a final state.

**Comment by candyj0311** [comment]
We are going to remove the high level takeaways from the Inventory for the time being.

**Comment by HeyCat** [comment]
![download_to_csv_modal](https://cloud.githubusercontent.com/assets/5464910/14568806/34e7d7a4-0309-11e6-9203-970ce24049ef.png)
![inventory-w-analysis](https://cloud.githubusercontent.com/assets/5464910/14568805/34e328ee-0309-11e6-9816-66c7e2112ffd.png)

**Comment by HeyCat** [comment]
Depending on whether or not an inventory has a subsequent analysis, the CTA button will change between "Go to analysis" or "Create analysis."

**Comment by bithavoc** [comment]
**Go to Analysis** button:

### as facilitator

* if none exists, show creation modal
* if one exists, go to that analysis
* if multiple analysis exists, go to the analysis listing

### as participant

* if none exists, user do not see Go to Analysis button at all.
* if one exists, go to that analysis
* if multiple analysis exists, go to analysis listing

Additionally, wire **Dashboard** button to the dashboard page for the inventory.
