### ISSUE TITLE
An inventory with multiple members should not appear multiple times in the list of inventories

### ISSUE THREAD

**Issue by bithavoc** [MobilityLabs/pdredesign-server#188]

**Comment by MakotoTheKnight** [comment]
This should be a simple matter of adjusting the query to only respect the `inventory_members` table as opposed to also looking at the owner, since the owner is part of the `inventory_members` collection.

**Comment by bithavoc** [comment]
Likely to be fixed by in https://github.com/MobilityLabs/pdredesign-server/pull/185 / https://github.com/MobilityLabs/pdredesign-server/pull/185/files#diff-ab04ede03b28ddf9c18d1827c56da017R5

**Comment by juliosantos** [comment]
@MakotoTheKnight That alone won't do, since a user can be both a facilitator or a participant in the `inventory_members` table.
@bithavoc That doesn't fix it but thanks for pointing it out.
