### ISSUE TITLE
Add inventory links in the list of inventories

### ISSUE THREAD

**Issue by bithavoc** [MobilityLabs/pdredesign-server#192]
The list of inventories and assessments is implemented between `common_list` and `entry_view`, assessment already works so for inventories we'd need to add a condition in `entry_view.html` similar to what we already do for assessments.

Example:

```
<div class="links" ng-if="isInventory === 'true'">
        <div class="repeat" ng-repeat="link in entry.orderLinks(entity.links)">
          <inventory-links
              data-title="{{link.title}}"
              data-active="{{link.active}}"
              data-type="{{link.type}}"
              data-id="{{entity.id}}"
              data-consensus-id="{{entity.consensus.id}}"
              data-role="{{role}}">
          </inventory-links>
  </div>
</div>
```

**Comment by candyj0311** [comment]
Depends on #144

**Comment by MakotoTheKnight** [comment]
This depends on  #144.

**Comment by candyj0311** [comment]
@MakotoTheKnight Be sure to add a screenshot.

**Comment by MakotoTheKnight** [comment]
Effectively, we're going to create links here to mimic the behavior of the assessments.  State 0 - the draft state - is straightforward, but we will require some decisions around wording when talking about "consensus" - do we want to replace that with "Create Analysis"?

![state0](https://cloud.githubusercontent.com/assets/1821302/14477511/93d125ee-00cb-11e6-8080-cbb3c4d50392.png)
![state1](https://cloud.githubusercontent.com/assets/1821302/14477512/93e6eece-00cb-11e6-9a71-0cc422b002db.png)
![state2](https://cloud.githubusercontent.com/assets/1821302/14477513/93e7c628-00cb-11e6-9505-04374ec07326.png)
