### ISSUE TITLE
Analysis report view markup

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#194]
We need to agree on where items are going to live and to figure out routes.

**Comment by candyj0311** [comment]
We need to agree on where items are going to live and to figure out routes.

**Comment by HeyCat** [comment]
![inventory analysis report](https://cloud.githubusercontent.com/assets/5464910/14572917/a6f9bda6-031f-11e6-840d-7c937a775728.png)

**Comment by bithavoc** [comment]
Following assessment's convention, the URL will likely be [`/inventories/:id/report`](https://github.com/MobilityLabs/pdredesign-server/wiki/UI-Routes#assessmentsidreport)

**Comment by MakotoTheKnight** [comment]
I would consider that to be a child of inventories, so likely `/inventories/:inventory_id/analysis/:id/report`.

**Comment by candyj0311** [comment]
The plus buttons under review open up to reveal the products that were tagged to each category. The Compare info should be in the Inventory.

**Comment by MakotoTheKnight** [comment]
Ensure that the `usage_questions.usage` column is reflected back as an actual percentage relative to 1, and not a text.

**Comment by candyj0311** [comment]
The EdSurge links are here: https://drive.google.com/open?id=1F4O03MRrDv4ybHp9vdRl0LscEPSyAqu9vAcanpV7qWk

**Comment by candyj0311** [comment]
@HeyCat We should add a column showing the data sets added for each category.

**Comment by HeyCat** [comment]
![inventory analysis report](https://cloud.githubusercontent.com/assets/5464910/14823066/2583d9d6-0b9f-11e6-9ce6-e21df6c944a0.png)

Added a column to show the number of data sets contributing to the progress of the pd category.

**Comment by MakotoTheKnight** [comment]
After talking this over with @bithavoc, we're thinking of splitting this task up into one that captures the frontend styles and one that wires the backend together.

**Comment by bithavoc** [comment]
I'll be adding "Share report URL" in the sidebar for inventories report as well.

**Comment by candyj0311** [comment]
@bithavoc The mockup is currently being updated to include high level takeaways (similar to what's in the RA) at the bottom.

**Comment by candyj0311** [comment]
Mockup updated to include High Level Takeaways like we have in the Readiness Assessment: 
![inventory analysis report](https://cloud.githubusercontent.com/assets/10750162/15156459/23ccbc9a-16b5-11e6-87ab-46be223a3f9d.png)

**Comment by candyj0311** [comment]
![analysis report](https://cloud.githubusercontent.com/assets/10750162/15159068/ac74f408-16c0-11e6-8bae-368fd4237a86.png)

**Comment by bithavoc** [comment]
Just a few highlights:

* We'll remove both the asterisk from the Category column header and the link to expand info
* Both Compare listings only include products discussed in analysis categories.
* Sidebar banner changes dynamically according to #1 priority, links goes to [client's website as listed here](https://docs.google.com/spreadsheets/d/1F4O03MRrDv4ybHp9vdRl0LscEPSyAqu9vAcanpV7qWk/edit#gid=893402460)
* **Save** only saves the takeaways, it doesn't persist the sorting of any of the columns in the report.

**Comment by HeyCat** [comment]
![inventory analysis report](https://cloud.githubusercontent.com/assets/5464910/15294505/8adad396-1b5a-11e6-81e2-48d481cbcdd4.png)

With expanded products view and updated Edsurge sidebar

**Comment by MakotoTheKnight** [comment]
Increase scope:  Ensure that the flow for creating an analysis is fully functional.
