### ISSUE TITLE
Analysis Create Page

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#195]
We should be able to reuse a lot of what we put together for the Inventory Create Page. We will need to have a listing of inventories for users to select from in Step 1. Participants and facilitators from that inventory should be brought over from the Inventory. Facilitators can add/manage additional facilitators, but not participants.

**Comment by candyj0311** [comment]
![image](https://cloud.githubusercontent.com/assets/10750162/14427172/4e006b5c-ffc1-11e5-92f6-7882a50e5c4f.png)

**Comment by candyj0311** [comment]
We'll need to create the controllers for this.

**Comment by juliosantos** [comment]
@MakotoTheKnight I'm already on this, is there anything you'd like to add?

**Comment by MakotoTheKnight** [comment]
I don't think there's much else I need to add for this one; just be sure that the learning questions piece is functional for analyses as well.  It is already polymorphic and supports both inventories and assessments.

**Comment by candyj0311** [comment]
Updated copy for the e-mail: The goal of the Data & Tech Analysis is to get the big picture of data and technology systems that support professional learning in your district. The Analysis consists of an in-person discussion of how well current data systems, technology infrastructure, and product purchases are aligned to professional development goals.
To participate along with your colleagues, you must first register with the PDredesign. Once registered, you'll have ongoing access to the analysis and results. Please contact <facilitator full name> with any questions at <facilitator email>.

**Comment by juliosantos** [comment]
(moving this here so it doesn't get lost in the channel)

@candyj0311:

> Facilitators can add/manage additional facilitators, but not participants.

This is slightly ambiguous. Could you expand on it a bit please?

**Comment by juliosantos** [comment]
We decided to interpret this requirement as "only facilitators can add/manage participants and facilitators". This is because:

1. It's what's already done
2. It makes sense. And even if it doesn't, if a facilitator wouldn't invite participants anyway, they can just not invite participants.

This would involve removing the "add participant" button, and changes to the "invite new participants" and "manage permissions" directives so that `role` can only be set to "facilitator".

**Comment by juliosantos** [comment]
@candyj0311 @HeyCat In step 1, is the inventory dropdown required? Should it be disabled?

**Comment by juliosantos** [comment]
@HeyCat says yes to both
