### ISSUE TITLE
New Analysis Modal (No Inventory)

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#196]
If a user does not have a completed inventory, this modal should appear when they begin the process of creating an Analysis.

**Comment by candyj0311** [comment]
![image](https://cloud.githubusercontent.com/assets/10750162/14427547/599bb1d6-ffc3-11e5-809e-4a63d5a838da.png)

**Comment by candyj0311** [comment]
I'll update the lorem ipsum with real copy.

**Comment by candyj0311** [comment]
Copy: The Data & Tech Analysis needs to be linked to a Data & Tech Inventory to be most effective. If you've already built an inventory, check to make sure you are a participant or facilitator of that inventory in order to create an analysis. You can also start a new inventory by clicking below.

**Comment by juliosantos** [comment]
@candyj0311 I'll assume the "Save" button should have been dropped from the mockup, let me know if I'm wrong.

**Comment by candyj0311** [comment]
@juliosantos: Yes, that Save button doesn't do anything. @heycatrobinson LMK if you want any changes to the modal beyond dropping the unnecessary Save. I can't think of another modal that behaves like this, so I don't think there's a standard to maintain around buttons to display.

**Comment by HeyCat** [comment]
![new-analysis-no-inventory](https://cloud.githubusercontent.com/assets/5464910/14644914/ae126be2-0621-11e6-9e1a-d103d2124c6f.png)
