### ISSUE TITLE
New Analysis Modal (User Has An Inventory)

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#197]
If the user does have 1 or more inventories, this modal should appear:

![image](https://cloud.githubusercontent.com/assets/10750162/14427715/f3e21bc2-ffc3-11e5-9bcc-f2f8ddaac96a.png)

Copy: Facilitate the Data & Tech Analysis process for your district by creating a new analysis and selecting an inventory to connect to it. Click here to view current analyses for your district or to participate in an existing analysis.

**Comment by candyj0311** [comment]
We will need to connect the inventories so that the user can select one of them in this modal.

**Comment by candyj0311** [comment]
Copy: Facilitate the Data & Tech Analysis process for your district by creating a new analysis and selecting an inventory to connect to it. Click here to view current analyses for your district or to participate in an existing analysis.

**Comment by juliosantos** [comment]
Create new Analysis models. An analysis `belongs_to` an inventory, and and inventory `has_one` analysis.

**Comment by MakotoTheKnight** [comment]
@HeyCat @candyj0311 Analogous to our existing tools, would the button to create this also live on the home page?

**Comment by candyj0311** [comment]
Yes. @HeyCat has a mockup.

**Comment by juliosantos** [comment]
@candyj0311:
0. Who can create analysis?
0. Should "inventory name" in the mockup above be just "name"? Does it relate to the inventory?
0. Seems a bit redundant to choose a district and an inventory unless, of course, you allow the user to choose a different district to the inventory's.

**Comment by candyj0311** [comment]
0. A facilitator of an inventory. 
0. Good catch - it should be "Analysis Name."
0. Agree - we should be able to just have the user select an inventory since each inventory is tied to a district already.

**Comment by juliosantos** [comment]
@candyj0311 
1. An inventory can have many facilitators, so I'll assume you mean all of them. I suppose the inventory owner too, right?

**Comment by juliosantos** [comment]
@candyj0311 
3. Does this mean "remove the district box"?

**Comment by candyj0311** [comment]
1 & 3. Yes.

**Comment by candyj0311** [comment]
We need to link "here" in the copy to the user's Analysis List Page (where all the analyses for that district and that the user is a part of are).
