### ISSUE TITLE
Analysis - "Edit Consensus"

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#198]
Porting over the readiness assessment in the correct format; we need to determine what data structure we want to use that will work best with adding products to a category.

**Comment by candyj0311** [comment]
The category names and descriptions can be found here, @MakotoTheKnight: https://docs.google.com/spreadsheets/d/1ladm2pK-bSp9VVSA8mra8VsGPg1p6GxG2klrEY8ROFE/edit#gid=0

**Comment by MakotoTheKnight** [comment]
Development:  we're going to want to break this out into pieces that can be worked concurrently.

**Comment by candyj0311** [comment]
@candyj0311 will add info from #234 and #235.

**Comment by candyj0311** [comment]
![image](https://cloud.githubusercontent.com/assets/10750162/14788613/b62cfc70-0ad6-11e6-87c9-a1d1b25f1ff2.png)
