### ISSUE TITLE
Analysis Dashboard Page

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#199]
This is very similar to the Inventory Dashboard.

**Comment by candyj0311** [comment]
@HeyCat will add the mockup.

**Comment by HeyCat** [comment]
![analysis_dashboard](https://cloud.githubusercontent.com/assets/5464910/14646572/f87e08d4-0627-11e6-958c-a3f560e4264b.png)

**Comment by candyj0311** [comment]
We will need to have a listing of inventories for users to select from in Step 1. Participants and facilitators from that inventory should be brought over from the Inventory. Facilitators can add/manage additional facilitators, but not participants.

**Comment by candyj0311** [comment]
@HeyCat If a participant wants to change the date of the meeting, where would they do that?

**Comment by bithavoc** [comment]
@candyj0311 This is the analysis dashboard page, in the sidebar I see a button called **Dashboard**. where should that go?

**Comment by HeyCat** [comment]
![inventory analysis report](https://cloud.githubusercontent.com/assets/5464910/15157564/3b3a7778-16ba-11e6-8fb0-1394c70bb52b.png)

**Comment by HeyCat** [comment]
![analysis_dashboard](https://cloud.githubusercontent.com/assets/5464910/15157584/533649e2-16ba-11e6-9dd6-a36712022817.png)

**Comment by bithavoc** [comment]
@HeyCat are we sticking to the primary button on top of the analysis schedule summary?

**Comment by HeyCat** [comment]
![analysis_dashboard](https://cloud.githubusercontent.com/assets/5464910/15157752/f4f3987a-16ba-11e6-9b2a-f6fa497dff67.png)

**Comment by HeyCat** [comment]
uploaded the old one by accident, see above...and thanks for your patience!

**Comment by bithavoc** [comment]
@candyj0311 where is the **Go to Analysis** button supposed to redirect? analysis assign, consensus, responses?
