### ISSUE TITLE
If a user has multiple invitations, they'll all be destroyed as soon as they create an account

### ISSUE THREAD

**Issue by juliosantos** [MobilityLabs/pdredesign-server#215]
We noticed this while addressing #214. We were running `UserInvitation.find_by(email: "..").destroy` which offers no guarantees as to which invitation is destroyed.

**Comment by MakotoTheKnight** [comment]
My belief would be that it should be safe to destroy all invitations if one is fulfilled, but as part of this task it would be worth investigating how many multiple invitations exist in production.

**Comment by MakotoTheKnight** [comment]
From what I can deduce of the system, we did have this setup, but this does not appear to be the case anymore; we appear to destroy invitations based on token.

Further, I see no issue with multiple invitations being destroyed upon registration; the invitation was created to spur registration originally and once its purpose has been fulfilled, it shouldn't be around anymore.

To further complicate matters, it is impossible to ascertain when these invitations were created as there is no timestamp information available on the user_invitations table, so it's tough to determine if any invites in production are recent or reminiscent of an older configuration.

I do not see this as an issue necessarily, but we may wish to keep this in our minds should we decide to rework the invitations core piece.
