### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#227]
The FAQ page needs to be updated to include the new tools. The FAQ for all tools will live on one page. We'd like it to be similar to what we did for ChatWisdom where you can click on a tool name and navigate to that part of the FAQ on the page.

**Comment by HeyCat** [comment]
![faq_page2](https://cloud.githubusercontent.com/assets/5464910/14646234/b5b05af8-0626-11e6-9199-c9a505131ff1.png)

**Comment by HeyCat** [comment]
Questions will already have answers listed (no interaction) and the sidebar to the right contains # links to jump to the portion of the page with that info

**Comment by candyj0311** [comment]
We have several questions about PDredesign, so we should add PDredesign to the list of tools on the right.

**Comment by HeyCat** [comment]
![faq_page2](https://cloud.githubusercontent.com/assets/5464910/14988113/8da7787a-1120-11e6-9273-fcb7cdd8037d.png)
