### ISSUE TITLE
Home Page (logged in)

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#229]
This is what the user sees as Home when logged in.  @HeyCat will add the mockup once it's been updated.

**Comment by HeyCat** [comment]
![landing1](https://cloud.githubusercontent.com/assets/5464910/14657587/da19c5ec-065c-11e6-9db1-69405fca20a1.png)

**Comment by HeyCat** [comment]
![home_logged_in](https://cloud.githubusercontent.com/assets/5464910/14717161/19bd961c-07be-11e6-88b4-dca22a4d6107.png)

**Comment by MakotoTheKnight** [comment]
Should include work to standardize the way we create these types of buttons.

**Comment by candyj0311** [comment]
We should flip the location of the Facilitate an Inventory and the Go to Assessment List links in the RA so they're consistent with the D&T tools.
