### ISSUE TITLE
Export Analysis Data to CSV

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#233]
This should be very similar to what we use for the RA since the formats are similar.

**Comment by HeyCat** [comment]
![inventory-w-analysis](https://cloud.githubusercontent.com/assets/5464910/14604730/1bf94eda-0543-11e6-98b4-0134cd814531.png)
![download_to_csv_modal](https://cloud.githubusercontent.com/assets/5464910/14604731/1bfb870e-0543-11e6-8178-7f50320bc1f3.png)

**Comment by candyj0311** [comment]
Depends on #199.

**Comment by candyj0311** [comment]
The table should look something like this. This one has some dummy data: https://docs.google.com/spreadsheets/d/16SWaWb3AxAxFaenLpEBUhXjmiF72r8pCVe9_s6DLcHA/edit#gid=0

* If nothing is entered for data or products, 0 should be displayed. 
* If a category has no score, that cell should be left blank. 
* Category order should be determined by how they're ordered in the report (if they're been rearranged and saved, they should appear in that order on the CSV).

**Comment by candyj0311** [comment]
@juliosantos I was able to see this on staging earlier in the afternoon, but cannot currently.

**Comment by juliosantos** [comment]
@candyj0311 I didn't remove it or anything... Did you look in the right place? It's right there in the analysis consensus:
<img width="538" alt="screen shot 2016-05-26 at 07 40 22" src="https://cloud.githubusercontent.com/assets/365821/15565829/34f29de8-2315-11e6-8fa4-a76d3682e1c9.png">

**Comment by candyj0311** [comment]
LGTM. Would it be possible to use a bigger, redder arrow? ;)

**Comment by juliosantos** [comment]
@candyj0311 Bigger and redder I should be able to do, but for flashing I'd refer you to the Web King: http://www.webkinglasvegas.com/

:)
