### ISSUE TITLE
Add product to schema in Analysis

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#234]
Facilitators can add a product or data set to a schema (PD category) in the Analysis as evidence. 

They should click the "Add Product" link which makes a modal appear. They choose product(s) or data set(s) from the modal and it is added to the Data/Product entry field.

Depends on #235.

**Comment by HeyCat** [comment]
![analysis_add_product](https://cloud.githubusercontent.com/assets/5464910/14680353/ffcd5a0e-06ea-11e6-935b-25d4e80f0939.png)
![analysis_add_product_select](https://cloud.githubusercontent.com/assets/5464910/14680354/ffcd2c32-06ea-11e6-9eac-e79184156b41.png)
![Uploading analysis.png…]()

**Comment by HeyCat** [comment]
![analysis](https://cloud.githubusercontent.com/assets/5464910/14680398/2b8c1540-06eb-11e6-9652-3daef11c9a65.png)

**Comment by candyj0311** [comment]
The Supporting Data and Supporting Products should have a fixed height. If a facilitator adds tons of products to a category, a scroll bar will appear.

**Comment by jkshepperson** [comment]
Per Jason's request, combined this task with his current task for #266 because of the functionality overlap. Closing this task and updating 266 with the comments and information
