### ISSUE TITLE
Mark Inventory as "Up to Date"

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#239]
Users adding products and data sets to an inventory can click the button "Mark Inventory as up to date." The facilitators should be able to see that participants have completed their part of the inventory in the dashboard. 

This is similar to what we have for the RA.

**Comment by MakotoTheKnight** [comment]
Approach: 

- [ ] Create a new entity called `InventoryResponse` which we will use analogous to how RA is using `Response`. 
- [ ] Update the `Inventories::ParticipantStatus` code to leverage the state of the response.
- [ ] Update the UI to indicate the status and show an appropriate value when under "assessment" mode.
