### ISSUE TITLE
Add name to Data Entry

### ISSUE THREAD

**Issue by MakotoTheKnight** [MobilityLabs/pdredesign-server#240]
- [x] Add name column to `data_entries` table
- [x] Update form to require name to be entered on data entries
- [x] Be sure name is required on product entries

**Comment by juliosantos** [comment]
@MakotoTheKnight To your third point, there's a card for that: https://waffle.io/MobilityLabs/pdredesign-server/cards/570cdf9310535d9500faae3d.
Please either assign it to me and move it to Ready to start, or delete it :)

**Comment by juliosantos** [comment]
"Data Set Name"

**Comment by juliosantos** [comment]
@MakotoTheKnight actually, worry not, you're busy, I'll handle it

**Comment by juliosantos** [comment]
Last task captured on #209
