### ISSUE TITLE
Updated Landing Page

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#245]
This is what users see when they are not logged in. @HeyCat will attach the mockup once it's finished being updated.

**Comment by HeyCat** [comment]
![home_logged_out3](https://cloud.githubusercontent.com/assets/5464910/14958330/4a4fdf04-1058-11e6-8ee3-b17ee0f9e66b.png)

**Comment by HeyCat** [comment]
![dta_imac](https://cloud.githubusercontent.com/assets/5464910/15079591/6a2541ca-1387-11e6-8eb6-3f069ec2bc72.png)
![dta](https://cloud.githubusercontent.com/assets/5464910/15079592/6a25a16a-1387-11e6-994b-661f8e8f09cd.png)
![dti_imac](https://cloud.githubusercontent.com/assets/5464910/15079596/6a2a1f24-1387-11e6-80e6-aae481bed94e.png)
![dti](https://cloud.githubusercontent.com/assets/5464910/15079593/6a27b6f8-1387-11e6-8184-2a06af69851f.png)
![ra_imac](https://cloud.githubusercontent.com/assets/5464910/15079594/6a2861de-1387-11e6-905e-a39b7b79aeb8.png)
![ra](https://cloud.githubusercontent.com/assets/5464910/15079595/6a299496-1387-11e6-848a-220ccc18fa8f.png)

**Comment by HeyCat** [comment]
Still figuring out the hero and footer images, but I will upload once they are final!

**Comment by HeyCat** [comment]
![footer_image](https://cloud.githubusercontent.com/assets/5464910/15084052/02a6c182-139f-11e6-973d-c9b4ae7a1582.png)
![hero_image](https://cloud.githubusercontent.com/assets/5464910/15084053/02aeecfe-139f-11e6-8dbc-8bca370f1a4f.png)

**Comment by candyj0311** [comment]
We should remove Amanda Smith's quotation and name/company. I am waiting on the go ahead for a replacement.
