### ISSUE TITLE
Modify Schedule button functionality on Inventory Dashboard

### ISSUE THREAD

**Issue by MakotoTheKnight** [MobilityLabs/pdredesign-server#261]
Make this button functional.  It should allow whomever clicks it to adjust the deadline of the inventory.

**Comment by candyj0311** [comment]
We need designs for the modal and date picker used for this (should already exist in the RA).

**Comment by HeyCat** [comment]
<img width="758" alt="screen shot 2016-04-29 at 15 41 49" src="https://cloud.githubusercontent.com/assets/5464910/14927759/c6a73d74-0e21-11e6-9ccf-9f43a3a19ce3.png">
