### ISSUE TITLE
Analysis - Make rubrics polymorphic

### ISSUE THREAD

**Issue by MakotoTheKnight** [MobilityLabs/pdredesign-server#265]
To support allowing analyses create a consensus, make rubrics polymorphic so that we can hook into this directly.

- [x] Migrate to polymorphic type "tool"
- [x] Ensure there are indexes based on type
- [x] Migrate all existing rubrics to use "Assessment"

**Comment by MakotoTheKnight** [comment]
@juliosantos:  If it's all right with you, I'll base this work off of #195.  I'd like to be sure I have the model I want to use with polymorphism for smoke testing purposes.

**Comment by juliosantos** [comment]
@MakotoTheKnight All fine by me, but remember it hasn't been reviewed yet!

**Comment by MakotoTheKnight** [comment]
@jkshepperson and @candyj0311:  Note that none of the changes in this work are visible to the end user, but a smoke test of consensus and ensuring that there is no aberrant behavior when performing a consensus would suffice.
