### ISSUE TITLE
Analysis Consensus - Frontend (partially wired)

### ISSUE THREAD

**Issue by MakotoTheKnight** [MobilityLabs/pdredesign-server#267]
Create the layout for the consensus page.

![](https://cloud.githubusercontent.com/assets/10750162/14788613/b62cfc70-0ad6-11e6-87c9-a1d1b25f1ff2.png)

The consensus pieces should not be wired in at this time, but the Learning Questions are eligible to be.

**Comment by MakotoTheKnight** [comment]
In some preliminary findings that I've done, the consensus form doesn't support skipping questions.

**Comment by HeyCat** [comment]
![analysis_add_data_select](https://cloud.githubusercontent.com/assets/5464910/14926606/eb60ab16-0e1a-11e6-82dd-74a83876b6ef.png)
![analysis_add_product_select](https://cloud.githubusercontent.com/assets/5464910/14926610/eb66237a-0e1a-11e6-900c-19c7e7563e4a.png)
![analysis_add_product](https://cloud.githubusercontent.com/assets/5464910/14926607/eb64d754-0e1a-11e6-85e1-06813a8c965a.png)
![analysis_add](https://cloud.githubusercontent.com/assets/5464910/14926608/eb64d9de-0e1a-11e6-9107-f81304a47718.png)
![analysis_containing_one_data_entry](https://cloud.githubusercontent.com/assets/5464910/14926609/eb660872-0e1a-11e6-89a0-12da637c5f7f.png)

**Comment by jkshepperson** [comment]
Per Sprint Planning today (5/2/16): 

We will merge #235 with this ticket in terms of scope and functionality and close #235.

Additional clarity:
- do not include pagination functionality at this time (we will create another ticket for that functionality if it is needed)

- for scope: the product and data entries that can be selected from the pop up must be from the inventory. Products/data sets that are from other inventories should not be shown as an optional selection.

**Comment by juliosantos** [comment]
We will merge #268 with this ticket in terms of scope and functionality and close #268.
