### ISSUE TITLE
Analysis Consensus - Frontend (fully wired)

### ISSUE THREAD

**Issue by MakotoTheKnight** [MobilityLabs/pdredesign-server#268]
Fully wire in the consensus frontend with the backend.

Depends on #266

**Comment by MakotoTheKnight** [comment]
We have a pop-up modal associated with the readiness assessment that warns a user if they're finishing the consensus prematurely.  Do we wish to incorporate that here as well?

**Comment by candyj0311** [comment]
@MakotoTheKnight Yes, we should.

**Comment by juliosantos** [comment]
@candyj0311 Please note that this piece will be reusing components currently in place for an assessment consensus. When QAing, plese ensure no regressions occurred with those.
