### ISSUE TITLE
Edit product and data inventory entries

### ISSUE THREAD

**Issue by jkshepperson** [MobilityLabs/pdredesign-server#275]
When viewing the Edit Inventory page, users need to be able to easily edit or make changes to their existing product and data entries.

1. When user lands on Edit Inventory page, display all product or data entries with an edit icon next to their row.
2. When clicked, display the existing product/data entry modal with all available information pre-populated in the appropriate fields. 
3. Allow users to make changes to the fields and click 'Done' to save their work. 
4. Reflect the new changes and updates in the system.

**Comment by candyj0311** [comment]
Covered in #299.
