### ISSUE TITLE
When viewing an inventory dashboard, both participants and facilitators should be displayed

### ISSUE THREAD

**Issue by jkshepperson** [MobilityLabs/pdredesign-server#283]
When accessing an inventory dashboard, currently only participants are displayed in the 'participants' area. In the Readiness Assessment, we display both the participants and facilitators associated with the Inventory.

1. the creator of the inventory should be displayed in the participant section of the inventory
2. added participants should be displayed in the participant section
3. network partners should *not* be displayed in the participant section

![image](https://cloud.githubusercontent.com/assets/15215098/14896186/802bb596-0d4a-11e6-9faf-948fca114d09.png)

**Comment by MakotoTheKnight** [comment]
This will be easier to rectify with the new Unified Permissions work.

**Comment by MakotoTheKnight** [comment]
Duplicated by #286.
