### ISSUE TITLE
When creating a new inventory, date of inventory is incorrect

### ISSUE THREAD

**Issue by jkshepperson** [MobilityLabs/pdredesign-server#285]
When creating a new inventory, the date chosen on the modal, does not correctly reflect on the finished page.

Steps to reproduce: 
1. Clicked 'Start Data Tech Audit' 
2. Entered information for a new inventory and selected due date: 05/02/2016
3. Clicked 'Create'
4. On the next page, the due date field is displaying: 05/01/2016

From Jason: potentially has to do with the timezones associated with the date picker functionality.

![image](https://cloud.githubusercontent.com/assets/15215098/14896847/7ab2c4bc-0d4d-11e6-945a-c3a994e84686.png)

![image](https://cloud.githubusercontent.com/assets/15215098/14896868/8cc9a2f6-0d4d-11e6-992a-0c817e92ea7e.png)

**Comment by candyj0311** [comment]
This is also the case in the Analysis.
