### ISSUE TITLE
When creating a new inventory, added participants do not display on the assign inventory page.

### ISSUE THREAD

**Issue by jkshepperson** [MobilityLabs/pdredesign-server#286]
When creating a new inventory, if a user selects to add participants and then selects a participant, when they save the participant added does not display on the page.

Steps to reproduce: 
1. Created new inventory (ID:15) What Would Beyonce Do
2. Added the user 'Pat Agonia' from the modal and clicked 'Done'
3. When the modal closed, Pat Agonia does not display on my page.

![image](https://cloud.githubusercontent.com/assets/15215098/14896964/0829d33a-0d4e-11e6-853c-c24defe1dfa6.png)

**Comment by MakotoTheKnight** [comment]
This will be addressed with the Unified Permissions Scheme.

**Comment by MakotoTheKnight** [comment]
This will be fixed starting with inventories and analyses (unification task #400).
