### ISSUE TITLE
User whose accounts were created in the invite flow have trouble logging in

### ISSUE THREAD

**Issue by juliosantos** [MobilityLabs/pdredesign-server#290]

**Comment by juliosantos** [comment]
from @MakotoTheKnight's comment on #195:

> We've got a similar issue with accounts being created in the invite flow as we did with inventories a while back; if we create an account and invite them with those credentials, that account cannot be logged in to

**Comment by seanperkins** [comment]
I think this might be fixed. Lets verify we can close this.

**Comment by MakotoTheKnight** [comment]
We require a fix for the Analysis flow; Assessments and Inventories are covered.

**Comment by seanperkins** [comment]
Thanks for confirming it is still open.
