### ISSUE TITLE
Text emails show HTML tags

### ISSUE THREAD

**Issue by juliosantos** [MobilityLabs/pdredesign-server#291]

**Comment by juliosantos** [comment]
From @MakotoTheKnight's comment on #195:

> Text-based emails show HTML tags. This may be a holdover from inventories in which it does a similar thing, so we will create a task to capture this.

**Comment by MakotoTheKnight** [comment]
Expanding the scope of this task a bit - legacy assessment emails did not incorporate the custom message (which is the source of bogus HTML tags to begin with).  In addition to removing the HTML tags from this, we will also incorporate the custom message with assessments.

**Comment by HeyCat** [comment]
In the assessment, the custom message did appear in the original email. The inventory and analysis email did not have tags on the originals 👍
