### ISSUE TITLE
Product/Data Entry inventory changes: deleting entries

### ISSUE THREAD

**Issue by jkshepperson** [MobilityLabs/pdredesign-server#292]
As a facilitator or participant user, I need to have the ability to remove or "delete" product entries or data sets from the inventory in-case I made a mistake or entered a duplicate entry. 

As a facilitator, I need the ability to view deleted product or data set entries and to bring them back to the main inventory, in-case they were deleted by mistake or our plans changed and we needed additional entries represented.

Specific criteria:
- participants and facilitators should be able to remove a product and data set entry by clicking the 'x' icon next to the product or data set entry row. 
- facilitators should be able to view checkboxes labeled 'Show deleted products' and 'Show deleted data' respectively
- when a facilitator checks the 'Show deleted products' or 'Show deleted data' checkbox, we should display the deleted product/data sets in grey, Work Sans text with the action "Move to main inventory" in blue.
- if the facilitator clicks the 'Move to main inventory' action for a given product or data set, we should display the deleted product/data set as active again in black, Work Sans font and make it visible.
- if a user chooses to export the inventory into a CSV file, do not display 'deleted' entries in the csv.

**Comment by HeyCat** [comment]
![inventory_one_product_entry](https://cloud.githubusercontent.com/assets/5464910/14925948/d91295da-0e17-11e6-96bc-fdd9926c425a.png)
![Uploading inventory_one_product_report2.png…]()

**Comment by HeyCat** [comment]
![inventory_one_product_report2](https://cloud.githubusercontent.com/assets/5464910/14925958/e8e372f4-0e17-11e6-934d-90d55ff560f7.png)

**Comment by jkshepperson** [comment]
also note the language used with the inventory status "complete" is no longer accurate (up to date would be preferred)

**Comment by candyj0311** [comment]
Shouldn't really be deleted, just hidden, e.g. through a is_deleted flag.

**Comment by HeyCat** [comment]
![main_inventory](https://cloud.githubusercontent.com/assets/5464910/15085546/fa10dc9c-13a8-11e6-9044-d23f20f4e658.png)

**Comment by MakotoTheKnight** [comment]
As part of this task, ensure that angular-xeditable is brought into the Gemfile with version 0.1.8.

**Comment by juliosantos** [comment]
@MakotoTheKnight I don't follow why angular-xeditable is needed. Let's touch base after standup.

**Comment by juliosantos** [comment]
@MakotoTheKnight I think a single endpoint makes more sense than two. It's a common pattern that the same route (say, `/inventories`) will yield different results based on authentication/authorization.  By the same token, `inventories/:id/product_entries` will yield different results based on whether they user's auth allows them to see soft-deleted items.

**Comment by jkshepperson** [comment]
one additional note here to update from changes made today: 
all changes listed above apply to the report page of the inventory (.../inventories/#/report) as we are adjusting the workflow to adjust to the tight timelines.

**Comment by juliosantos** [comment]
Font considerations were pushed to #297
