### ISSUE TITLE
Misc. Style Issues

### ISSUE THREAD

**Issue by jkshepperson** [MobilityLabs/pdredesign-server#297]
Bucket card to hold all style issues found during testing and development. Checklist below will house all style related issues found through PDredesign with additional information and artifacts found in this [Style Issue Document](https://docs.google.com/a/mobility-labs.com/document/d/1QsAWTCKoSXij_yVQm4ux5w701GWkUM-LJwKHy0SPK9M/edit?usp=sharing)

- [x] Product/data set tables need to be updated to match new styles
- [x] Search boxes should be unified and look like the mockup
- [x] Adding products modal, checkboxes need styling
- [x] Manage permissions modal, dropdown fields for Facilitator/Participant need styling 
- [x] Add participants modal, add spinner gif**
- [x] Margins of all the tool in home should be equal
- [x] Skipped questions should match the same style as answered questions (if a participant skips a question, the color bubble should be filled in with the color of the corresponding answer section - in our case, the skip selection is grey. This applies to the Readiness Assessment survey sections. See style doc for screenshots.
- [x] Hide the Skip This Question grey option on the RA consensus. Note: users should be allowed to submit the consensus even if they did not answer all of the consensus questions.
- [ ] Ensure color styles are consistent with (style guide found here)(https://drive.google.com/open?id=0B9NtJ8CQ_KsGZ1M5VU9aVFRfZXc)
- [ ] Universal sidebar width to avoid button text wrapping
- [x] Universal font: Work Sans (h1-h6) etc.
- [x] Buttons throughout app should have consistent styling
- [x] Universal spinner styles -tThe bg color is #EBECF0 at 50% alpha with the gif included in artifact doc
- [x] Save button should match 2 CTA styles
- [ ] Margins issues described below
- [ ] Survey text on all boxes should be changed to a darker grey and descriptive text changed to a bolder version of Work Sans for improved legibility
- [x] Text field for High Level Takeaways in Analysis Report should be same width as tables. Save button should be aligned to new right side of text box.

**Comment by HeyCat** [comment]
General margin issues 

![welcome_back](https://cloud.githubusercontent.com/assets/5464910/15128159/380b142a-1608-11e6-9838-3726d0adc9b9.png)
![facilitate_readiness_assessment](https://cloud.githubusercontent.com/assets/5464910/15128161/380cb802-1608-11e6-80df-8a09af9edab0.png)
![facilitatedt_assessment](https://cloud.githubusercontent.com/assets/5464910/15128158/380b2f82-1608-11e6-9988-45634774c7d0.png)
![list_view](https://cloud.githubusercontent.com/assets/5464910/15128160/380c1ece-1608-11e6-9297-15bf253c6ddf.png)

**Comment by candyj0311** [comment]
We should pull out the top issues and create new tickets to add to Backlog.

**Comment by juliosantos** [comment]
@HeyCat should the radio buttons be blue as well?

![](http://drop.whoisjuliosantos.com/9ii3/1BIK69pN+)

**Comment by juliosantos** [comment]
@candyj0311 @jkshepperson "Skip image should have indication on right hand side". It seems skipping isn't possible anymore, even though the button is still present in the case of the RA consensus.

**Comment by juliosantos** [comment]
@HeyCat «Universal spinner styles»

This is what it looks like without the updated gif (which is where, by the way?). Should we change the "Loading" text color to a darker colour too (see red arrow)?

![](http://drop.whoisjuliosantos.com/11oj3/yqDkLevP+)

**Comment by juliosantos** [comment]
We agreed to consider this task "done". There will be a new one with other style issues in more detail.
