### ISSUE TITLE
Clicking Name of Assessment/Inventory in List Does Nothing

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#302]
These appear clickable, but on click, nothing happens. This is true on Production and Staging.

One fix would be to just change the text so that it doesn't appear clickable. Another would be to have clicking on the name of an Assessment/Inventory/Analysis take you to the latest step in the process so that users can more easily navigate to what they need to work on.

**Comment by MakotoTheKnight** [comment]
We can remove the link-style text, which is a very light lift.

The piece preventing us from taking the user to the next "step" is that a user can be in many different states at once given an assessment, inventory, or analysis, and assuming which we should use would cause us some headaches.

**Comment by candyj0311** [comment]
In that case, let's change the link-style text then so it no longer looks clickable.

**Comment by jkshepperson** [comment]
Also looks good - all titles have their link-looking properties removed
