### ISSUE TITLE
Ensure that the user who creates an Analysis is registered as one of its facilitators

### ISSUE THREAD

**Issue by MakotoTheKnight** [MobilityLabs/pdredesign-server#307]
We currently have code that copies over the participants and facilitators of an inventory into a new analysis, but this code does not allow for the user who created the analysis to become a facilitator.

Any participant or facilitator on the original inventory may create an analysis.

Key points:

 - Change the controller to make use of the `AnalysisAuthorizer` to ensure its actions are protected.  This will need to be regression tested to ensure no breakage in flow.
 - Ensure that members of an inventory (both participants and facilitators) can create an analysis.
 - Update the `Analysis` model to ensure that whomever created it becomes a facilitator of it.  Right now, we're simply copying over all of the participants on the inventory which does not handle this case.

**Comment by jkshepperson** [comment]
Just tested - looks good, upon creating the analysis all users from the inventory are correctly pulled into the analysis.
