### ISSUE TITLE
When adding a Product Entry, connectivity products should be scoped to the current inventory

### ISSUE THREAD

**Issue by bithavoc** [MobilityLabs/pdredesign-server#311]
It seems like **Connectivity products** is showing products from other inventories, this should not be the case as Connectivity products should be scoped to other products in the current inventory.

Here's an screenshot of how, while trying to add a product in inventory **2**, it's displaying products from inventory **1**.
![](https://cloud.githubusercontent.com/assets/219289/15188045/67f87706-1769-11e6-9599-c19977ff6a9c.png)

Here we can see that this product belongs to inventory **1**:
![](https://cloud.githubusercontent.com/assets/219289/15188128/dcf7e834-1769-11e6-9242-3e5aa1876db0.png)

**Comment by MakotoTheKnight** [comment]
It looks like this pulls the products in based on the district and not necessarily the specific inventory attached to it.  Given that the inventories created would all be associated with the same district, is this something we could consider truly aberrant?  I defer to @candyj0311 on this particular aspect.

**Comment by candyj0311** [comment]
That's a good point @MakotoTheKnight. This becomes an issue when a district has several inventories (which could occur in different scenarios), but should not immediately be an issue for users. Let's deprioritize this for now and come back to it later.

**Comment by HeyCat** [comment]
Verified that in prod a product wrongly populates in the inventory to which it is not associated. In staging, new inventories are completely empty as expected.
