### ISSUE TITLE
Modify Schedule Button Does Not Work w/Past Dates

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#327]
The behavior suggests that a user can adjust the schedule so that if a due date is in the past, it can be moved to the future.

When a facilitator tries to move the due date from the past to the future, the due date is not updated once a new one is selected.

**Comment by HeyCat** [comment]
Verified that in the latest staging push, user cannot schedule an assessment consensus meeting in the past. User gets an error message within the modal popup.
