### ISSUE TITLE
Remove Video

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#337]
The embedded video on the home page is out of date and can be removed.

**Comment by candyj0311** [comment]
![video](https://cloud.githubusercontent.com/assets/10750162/15610823/e14cfbf6-23ec-11e6-8e45-c9aa94d1c007.png)

**Comment by jkshepperson** [comment]
This is also present in the following places and should be removed from here as well as the homepage (listed above): 
- RA: Assessment List sidebar
- RA: Dashboard views
- RA: Report pages
- Inventory: Inventory List sidebar
- Analysis: Analysis List sidebar
