### ISSUE TITLE
Inventory participants should be able to create analyses on that inventory

### ISSUE THREAD

**Issue by juliosantos** [MobilityLabs/pdredesign-server#344]
The `InventoryAuthorizer` is set up to prevent this, but shouldn't be.

**Comment by candyj0311** [comment]
Participants should be able to create an Analysis from the Analysis List page and the PDredesign home page. They should be able to choose any Inventory to link to that Analysis.

**Comment by candyj0311** [comment]
This touches on an item in #307.

**Comment by jkshepperson** [comment]
I tested this yesterday and it worked successfully. For reference, here is the inventory i created as a facilitator: '344 Test Inventory - Participant Creates Analysis' and the analysis i created as the participant: http://staging.pdredesign.org/#/inventories/29/analyses/19/report
