### ISSUE TITLE
Hide Consensus Link in Analysis List

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#350]
On the Analysis List page, there is a View Consensus link and a Consensus link. Clicking the Consensus link generates a scary red pop-up. We should fix this flow by a) not displaying that link at all or b) directing users to an Analysis “view” page where they can preview the categories and scoring, but not do any scoring or enter any evidence. If we go with b), we should change the Consensus link to View Consensus. 

![consensus was not created](https://cloud.githubusercontent.com/assets/10750162/15518041/efa55732-21c8-11e6-916b-3036eea6b1c2.png)

**Comment by candyj0311** [comment]
@juliosantos Any idea what is causing this to happen?

**Comment by juliosantos** [comment]
@candyj0311 this is related to but not exactly #344

1. The "Consensus" links is only seen by participants
2. It tries to create a consensus (a `Response`, as our backend knows it)
3. It errors because  we don't allow a participant to create a consensus

**Comment by candyj0311** [comment]
For right now, we're going to hide the Consensus link. In the future, we can create a View Consensus page for participants to preview the categories to help them prepare for the meeting. Participants can currently see categories in the Facilitation Guide.
