### ISSUE TITLE
Stay Connected Hidden by ZenDesk Help Widget

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#358]
The ZenDesk widget hovers over the Stay Connected Facebook and Twitter links. We should move them below the Privacy Policy/Terms of Use so that they aren't covered. We should also remove the Facebook link because it takes users to a page that does not exist.

**Comment by candyj0311** [comment]
<img width="1154" alt="screen shot 2016-05-27 at 8 20 12 am" src="https://cloud.githubusercontent.com/assets/10750162/15609147/f25b4d34-23e3-11e6-9965-3e36064ff74e.png">

**Comment by candyj0311** [comment]
<img width="1154" alt="stay connected" src="https://cloud.githubusercontent.com/assets/10750162/15609166/0bb6b8cc-23e4-11e6-94e5-c185e8aa889c.png">

**Comment by MakotoTheKnight** [comment]
No longer an issue; recent changes to the style have made this occurrence impossible.
