### ISSUE TITLE
Analysis Dashboard participant user profile box breaks button alignment

### ISSUE THREAD

**Issue by jkshepperson** [MobilityLabs/pdredesign-server#374]
When viewing an Analysis Dashboard page, in some cases - the user profile boxes seem to break the container surrounding the 'Add New Participant', 'Manage Permissions' etc. buttons.

![image](https://cloud.githubusercontent.com/assets/15215098/15757553/193a70fc-28d4-11e6-830a-74aec1026573.png)

**Comment by MakotoTheKnight** [comment]
No longer a bug; new styles have come along and fixed this particular issue.

![image](https://cloud.githubusercontent.com/assets/1821302/16786518/957f9fbe-4852-11e6-8dc7-d1b3998d4d9d.png)
