### ISSUE TITLE
Sidebar on privacy page and terms of use collapse content too much

### ISSUE THREAD

**Issue by seanperkins** [MobilityLabs/pdredesign-server#389]
Currently, when you view the following two pages the content is squished at a generous 1024px window size.
http://pdredesign.org/#/privacy
http://pdredesign.org/#/terms-of-use

**Comment by MakotoTheKnight** [comment]
Immediate thing that strikes me as odd for those pages is that they have the sidebar window attached to them.  We can remove that to see if this resolves the issue.

**Comment by HeyCat** [comment]
<img width="1033" alt="screen shot 2016-09-09 at 17 10 13" src="https://cloud.githubusercontent.com/assets/5464910/18403046/95b3f110-76b0-11e6-9fe2-c3b4c42b463a.png">
<img width="1081" alt="screen shot 2016-09-09 at 17 10 22" src="https://cloud.githubusercontent.com/assets/5464910/18403045/95b1e6ea-76b0-11e6-9ab3-49497c2e6ea8.png">

**Comment by HeyCat** [comment]
All fixed in prod!
