### ISSUE TITLE
Clean up "no-participants" error message

### ISSUE THREAD

**Issue by MakotoTheKnight** [MobilityLabs/pdredesign-server#392]
Currently, this is what it looks like:

<img width="778" alt="screen shot 2016-08-29 at 14 05 02" src="https://cloud.githubusercontent.com/assets/5464910/18061678/9e91a5a6-6df1-11e6-858a-7873a3a0dbb1.png">

This doesn't read as user-friendly, and should be reduced to:

"You must assign participants to this assessment."

**Comment by MakotoTheKnight** [comment]
This will have impacts with the Unified Permissions work.

**Comment by MakotoTheKnight** [comment]
This can be addressed with further work in the Unified Permissions Scheme; essentially, this involves completing the port of the UPS to assessments as well.

**Comment by HeyCat** [comment]
Tested in Staging and the error message is now user-friendly, but the meeting date is still the variable name in the error.
