### ISSUE TITLE
When I try to interact with an assessment after submitting my consensus meeting, I get an error.

### ISSUE THREAD

**Issue by seanperkins** [MobilityLabs/pdredesign-server#413]
Getting a 400 error when trying to add high level takeaways to assessment 265 as a district facilitator.

Error response is:
`{"errors":{"meeting_date":["must be set no earlier than 09/22/16"]}}`

These errors were not shown to me but were visible in my console.

The due date and consensus date are both in the future but I created a consensus ahead of schedule anyway and am now receiving an error.

I should not receive errors if I performed a consensus meeting before the scheduled due date or consensus date.

**Comment by MakotoTheKnight** [comment]
This isn't a bug, but is a bit of an edge case; we do not allow meetings to be created on the same day as the assessment has been created.  This would not normally occur in practice, and this particular behavior was introduced by fixing #327 (PR #397).
