### ISSUE TITLE
Add access request mailer for Analyses

### ISSUE THREAD

**Issue by MakotoTheKnight** [MobilityLabs/pdredesign-server#415]
Add the missing request mailer for analyses.  The style should be similar to Inventories.

**Comment by MakotoTheKnight** [comment]
Late discovery:  The URL for inventories was broken given that there was no feasible route that this particular one could hit to allow a user to grant permissions.  I'll be correcting this logic since it dovetails nicely with the grant method for ToolMembers.  No predicted change in work load size.

**Comment by HeyCat** [comment]
Both facilitator and participant access request emails were successfully sent in staging. 
![screen shot 2016-10-17 at 3 57 01 pm](https://cloud.githubusercontent.com/assets/5464910/19453259/78f88d2a-9482-11e6-9d2f-262efc2fbe11.png)
![screen shot 2016-10-17 at 3 56 56 pm](https://cloud.githubusercontent.com/assets/5464910/19453258/78f83e56-9482-11e6-933a-d3e3a7a0c970.png)
