### ISSUE TITLE
Capitalization issues on RA, Inventory and Analysis pages

### ISSUE THREAD

**Issue by jkshepperson** [MobilityLabs/pdredesign-server#424]
when creating a new RA, after the new RA is completed and the user is returned the list of RA's in the system, the word 'View' is spelled/written: 'VIew'. 

To replicate: 
1) log into PDredesign on staging
2) click Readiness Assessment to view the RAs
OB: RA titled "Fall Means Pumpkin Spice" image below

![image](https://cloud.githubusercontent.com/assets/15215098/19361390/7f9ccacc-9150-11e6-9a6a-a8c7ade37616.png)

**Comment by jkshepperson** [comment]
also the case in the Inventory List page as well: 

![image](https://cloud.githubusercontent.com/assets/15215098/19362049/0b4d198a-9153-11e6-84f5-39667105b2ac.png)

**Comment by jkshepperson** [comment]
Also a similar issue with the Finish & Assign link for an Inventory saved in 'Draft' state:

![image](https://cloud.githubusercontent.com/assets/15215098/19365205/b201d4c6-915f-11e6-8bc4-596ceb512812.png)

**Comment by MakotoTheKnight** [comment]
This is not a bug in either case; the text actually does display the lower case letters, but the font only appears to be missing the dot above the "i" in certain cases; it's not actually missing it.
