### ISSUE TITLE
View Inventories - Dashboard page 'Manage users' section user tile breaks

### ISSUE THREAD

**Issue by jkshepperson** [MobilityLabs/pdredesign-server#425]
When viewing an Inventory Dashboard page, the 'Manage Users' section contains an error in how the user tiles are displayed in the top section. User tiles seem to be cut-off (image below)

To reproduce:
1) Login to pdredesign on staging
2) click Data and Tech Inventory
3) click View Dashboard of the 'Fall Means Pumpkin Spice Inventory' 
Observe: participant tile issues

![image](https://cloud.githubusercontent.com/assets/15215098/19362104/4c3c5dc0-9153-11e6-90f5-4559d81126e4.png)

**Comment by jkshepperson** [comment]
Same goes for the Analysis Dashboard: 

![image](https://cloud.githubusercontent.com/assets/15215098/19364502/740f6988-915c-11e6-8d58-fd8fba807d19.png)

**Comment by MakotoTheKnight** [comment]
Those pages are all using the same component, so that'll be reflected in both of those spots.  We can look into what's going on there.

**Comment by jkshepperson** [comment]
just tested with an analysis, inventory and RA - all look great :)
