### ISSUE TITLE
Cannot add an Analysis to an Inventory

### ISSUE THREAD

**Issue by jkshepperson** [MobilityLabs/pdredesign-server#427]
When working within an Inventory -or- attempting to create an analysis from the Analysis section, a user cannot create an analysis without receiving an error. 

To reproduce:
1. login to pdredesign on staging (for my test i logged with jkshepperson@gmail.com- a facilitator on the Fall inventory I had just created)
2. click Data and Tech Analysis
3. Click 'Facilitate New Analysis'
4.

**Comment by MakotoTheKnight** [comment]
I see what's going on with this one; I'll be hotfixing it momentarily.

**Comment by jkshepperson** [comment]
got it! i'll pause my write up until i can retest when you're done...if all is well i'll just remove this card!

**Comment by jkshepperson** [comment]
All good with @MakotoTheKnight fix! moving to closed
