### ISSUE TITLE
Simplify permissions models

### ISSUE THREAD

**Issue by seanperkins** [MobilityLabs/pdredesign-server#59]
* Remove viewer user type, now just share by link
* District users can now be facilitator or participant only
* Network partners can be only facilitator

Should take a look at new requirements for Inventory invitations: https://docs.google.com/document/d/1IWKZAtGon0QuZAXbswjOpc2fWX3xZ9MDmG0qHbivHS4/edit#heading=h.e99matkveeo1

May also want to review this PR to see if we can use it to for permissions https://github.com/MobilityLabs/pdredesign-server/pull/49

**Comment by MakotoTheKnight** [comment]
Removing the viewer user type should mostly be done already with the work on #61 and #62.

**Comment by candyj0311** [comment]
* Remove role options from request access dialog for Network Partners - dialog shouldn't appear at all, behavior should be same as what district members see when they request access
* If an admin adds a new participant to an assessment and a Network Partner already exists with that e-mail address, then the Network Partner will be added as a Facilitator regardless of the role chosen in the dialog
  * If a user doesn't exist, the flow stays as it normally is
* When an admin manages participants, the admin can only choose Facilitator for Network Partners (disable selection for roles for Network Partners)

**Comment by bithavoc** [comment]
<img width="885" alt="screen shot 2016-02-22 at 10 04 11 pm" src="https://cloud.githubusercontent.com/assets/219289/13240398/40774ae6-d9b0-11e5-99ce-2a1c3411c9fb.png">

When there are existing network partners in assessments as `participants`(or really any role) it has become impossible to change it to `facilitator` since the option will be disabled from now on.

One solution is to migrate the permissions of all existing network partners to `facilitators` across all assessments in the platform.

@candyj0311 thoughts?

**Comment by candyj0311** [comment]
Do we know how many users this impacts and how active they are?

**Comment by bithavoc** [comment]
That's interesting, there are none.

*  **37** `assessments_facilitators`
*  **9** `assessment_viewers`
*  **0** `assessments_network_partners`

May be this is the reason why they want to remove the option for network partners, all of them choose to be facilitators.

**Comment by candyj0311** [comment]
That's good news for us then. Let's migrate the permissions then.

**Comment by bithavoc** [comment]
Sorry @candyj0311, I fetched wrong numbers, I'm supposed to look for **Network Partner** users currently playing `Participant` roles inside Assessments and we have **55** of those in production, we'll need to migrate them to `Facilitators` instead.

**Comment by bithavoc** [comment]
Working on it.

**Comment by candyj0311** [comment]
Ah, okay.

**Comment by candyj0311** [comment]
LGTM.
