### ISSUE TITLE
A facilitator can add a learning question for any tool

### ISSUE THREAD

**Issue by seanperkins** [MobilityLabs/pdredesign-server#63]
Learning questions are connected to the tool and district.

eg. If I have a readiness assessment, it has 2 learning questions, if I also have a tech inventory, it can have 3 different questions.

Questions are just user created sentences.

**Comment by MakotoTheKnight** [comment]
Do we have designs for this particular functionality?  Where would we be placing it in the application?

**Comment by MakotoTheKnight** [comment]
We require further clarification on this particular functionality.

**Comment by candyj0311** [comment]
@rickymetz Let us know if there's a more recent version that is one: https://drive.google.com/drive/u/0/folders/0B-nCEm5iPUjiMjNlbklaTnFaalk

**Comment by seanperkins** [comment]
@rickymetz Once we get an updated wireframe, this should be good.

**Comment by MakotoTheKnight** [comment]
Closing this task in favor of the decomposed tasks #77, #78, and #79.
