### ISSUE TITLE
Share report by link

### ISSUE THREAD

**Issue by bithavoc** [MobilityLabs/pdredesign-server#75]
* There will be only one share code per assessment
* A button to share will appear in the right side bar of the report page http://localhost:3000/#/assessments/45/report with a mail:to link to the report so it can be shared via email
* Report will be shown as non-facilitator model, which means, the **EDIT** button will be hidden and Dashboard and Consensus will be also invisible to the viewer user.
* In the navigation bar, only leave The brand logo and Sign-in/Signup action
* Only Facilitators will be able to share the link

**Comment by candyj0311** [comment]
Let's check with @rickymetz when he gets back - it seems like a useful enhancement might be to be able to share the link and also share by e-mail in one place.
