### ISSUE TITLE
Product Inventory:  Low Fidelity Sketches

### ISSUE THREAD

**Issue by MakotoTheKnight** [MobilityLabs/pdredesign-server#80]
Low fidelity mockups for the following pages:

 - About This Tool
 - Learning Questions modal (may be covered by an earlier task)

**Comment by seanperkins** [comment]
@rickymetz Aren't we getting rid of district goals at this time? I think we decided on that before the retreat.

**Comment by MakotoTheKnight** [comment]
@seanperkins:  That has indeed been removed.  I'll remove this from the task right now.
