### ISSUE TITLE
Product Inventory:  Add District Users to Inventory

### ISSUE THREAD

**Issue by MakotoTheKnight** [MobilityLabs/pdredesign-server#83]
Borrow from Steps 2 and 3 from the existing assessments flow and allow the facilitator to manage the participants and send an email out to others.

Attached image for reference:
 
![pasted image 0](https://cloud.githubusercontent.com/assets/1821302/13061138/2d2aa9c8-d3f3-11e5-8a63-763956047be7.png)

A facilitator must also be able to send reminders to all participants in case no one has responded.  This functionality is similar to what we already have in place for Assessments.

**Comment by candyj0311** [comment]
Wise words from Jason: make sure we're not copy-pasting wholesale the Readiness Assessment for this piece.

**Comment by candyj0311** [comment]
![image](https://cloud.githubusercontent.com/assets/10750162/13409181/c1390274-deff-11e5-8473-e94899b0601a.png)

**Comment by candyj0311** [comment]
![image](https://cloud.githubusercontent.com/assets/10750162/13409326/7b402666-df00-11e5-9c5c-8d9916fe6d55.png)

**Comment by bithavoc** [comment]
This issue will only focus on:

* When there district users that are not yet members of the inventory, it will show a link that triggers a modal listing all the district users that can be added to the inventory
* Only users from the district that are not network partners and haven't been added to the inventory can be added
* Once all intended users have been added from the district, modal can be close via **Done** or **X** button (upper right side of the dialog)
* The button *Add Users* currently look as a clickable label until we apply the style as part of https://github.com/MobilityLabs/pdredesign-server/issues/132
