### ISSUE TITLE
Landscape Analysis:  Results Page

### ISSUE THREAD

**Issue by MakotoTheKnight** [MobilityLabs/pdredesign-server#87]
![image](https://cloud.githubusercontent.com/assets/1821302/13061762/302415c0-d3f7-11e5-9cab-1cb0f00c6d9d.png)

**Comment by candyj0311** [comment]
For the time being, we should omit "Our district goals."

**Comment by candyj0311** [comment]
Changes have been made to this mockup. We should not start work on this until this issue is updated.

**Comment by candyj0311** [comment]
This is a duplicate.
