### ISSUE TITLE
Consensus Meeting Can Only Be Scheduled For the Future

### ISSUE THREAD

**Issue by candyj0311** [MobilityLabs/pdredesign-server#91]
Users can currently schedule consensus meetings in the past and then cannot fix it.

**Comment by candyj0311** [comment]
<img width="931" alt="screen shot 2016-02-16 at 11 42 16 am" src="https://cloud.githubusercontent.com/assets/10750162/13083854/c678c9aa-d4a4-11e5-939f-416bc87e5090.png">

**Comment by HeyCat** [comment]
<img width="1126" alt="screen shot 2016-08-29 at 13 45 29" src="https://cloud.githubusercontent.com/assets/5464910/18061099/674f4834-6def-11e6-90ed-a49dadef6789.png">

**Comment by HeyCat** [comment]
I was able to schedule the consensus meeting in the past, after having created the assessment in production.

**Comment by HeyCat** [comment]
<img width="778" alt="screen shot 2016-08-29 at 14 05 02" src="https://cloud.githubusercontent.com/assets/5464910/18061678/9e91a5a6-6df1-11e6-858a-7873a3a0dbb1.png">

**Comment by HeyCat** [comment]
The warning box for the meeting date worked successfully. Is there a way to make the variable names more friendly? Like removing the "participant_ids" variable and make the second warning say " Meeting date" rather than "meeting_date"

**Comment by MakotoTheKnight** [comment]
@HeyCat:  Those values do come directly from Rails, and that error message is fairly custom.  I can add it to the list of improvements to make.
