### ISSUE TITLE
Remove hardcoded permission ID for assessment permission routes

### ISSUE THREAD

**Issue by bithavoc** [MobilityLabs/pdredesign-server#99]
Currently the route to manage assessment permissions is as follows:

```rb
/v1/assessments/:assessment_id/permissions/:id(.:format)
```
The `:id` parameter is not being used at all which suggest this controller should have been mounted as part of the collection and not a nested resource.

This would also involve removing the hardcoded `:id` `1` in [manageParticipants.js](https://github.com/MobilityLabs/pdredesign-server/blob/master/app/assets/javascripts/client/directives/manageParticipants.js#L65)

**Comment by jkshepperson** [comment]
Duplicate intent of #251 - merging this information into #251 and closing the ticket
